### ISSUE TITLE
Setting correct page title

### ISSUE THREAD

**Issue by AndreyAttr** [AndreyAttr/Evo#39]
1) HtmlWebpackPlugin - need to figure out what its property **title: 'Evo'** do, because it doesn't change the page title. Check another property

2) Problem may be resolved with using Angular service
https://angular.io/docs/ts/latest/cookbook/set-document-title.html

**Comment by AndreyAttr** [comment]
1. It really changes it. But the secret is it doesn't work with HTML file(we use html-loader and it may only use what's written in the static HTML template file). Here:
https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates
it is said:

> Load a custom template (ejs by default see the FAQ for details)
> You can use the lodash syntax out of the box.

so I used ***.EJS** template file instead of ***.HTML** extension and by using lodash template syntax did substitution **<title> tag** value(from **<%= htmlWebpackPlugin.options.title %>**)

2. Angular service, as I understood what's written on https://angular.io/docs/ts/latest/cookbook/set-document-title.html, designed to provide possibility to change page title from specific component(logically, according to business rules) by using **Title** Angular's service. And this is not the same that required by this task.

**Comment by tapy-lappy** [comment]
maybe should close it? 👍

**Comment by AndreyAttr** [comment]
yes, of course
