### ISSUE TITLE
Remove ugly switch/case solution from dna-list.component

### ISSUE THREAD

**Issue by AndreyAttr** [AndreyAttr/Evo#40]
@AndreyAttr,
This temporary solution to update genes should be removed:

```
<div [ngSwitch]="mutationEnabled">
        <ng-template [ngSwitchCase]="false">
            <gene-component [dna]="dna">Place for gene...</gene-component>
        </ng-template>
        <ng-template [ngSwitchCase]="true">
            <gene-component [dna]="dna">Place for gene...</gene-component>
        </ng-template>
        <ng-template ngSwitchDefault>
            Incorrect value
        </ng-template>
    </div>
```
Intead of it we need to use simple code (just gene-component markup) which will update itself without any outside influence/actions as this switch/case is right now. **Quick fix:** maybe implemented as component interaction service.

**Comment by AndreyAttr** [comment]
This is very important:

> 3) gene.component.ts - added private variable **appState**(injected through constructor). Figured out interesting detail: that because we recreate GeneService manually(by using DI helper), we also recreate **AppState** instance(each time we generate GeneService - each time we generate new **AppState**) for MutationService(which is used by GeneService). But with this behaviour we MUST re-subscribe each time onto **mutationChanged$** event because it happens that we are overriding current **AppState**(with subscribers) with new **AppState**(that we just create, but it hasn't had any subscribers yet). So, we WIPED!!! current AppState!!! The very one thing AppState works - it because we use state = defaultState; to initialize AppState and when we add/remove DNA - we really work with selectedDnas/availableDnas from defaultState. This is temporary workaround and MUST be FIXED. Possible solution: we should avoid using AppState for creating GeneService/MutationService AND because we now have **AppState** property(injected through constructor) we probably should use it to create instances of these services and do not use creating their instances manually by DI helper.

So we have **ugly** but *working* workaround which we MUST eliminate. I'll change Mileston to MAJOR

**Comment by AndreyAttr** [comment]
Also - it works(switchs mutation) only on last added DNA. If you remove it - it won't work. So this workaround produces bug by itself.

**Updated**: checked. Yes, it's really true. Because we remove AppState with current subscriebers we lost subscriptions and it produces this wrong behaviour.

**Comment by AndreyAttr** [comment]
We need mutate all GNAs by clicking at that button. And maybe provide **_Mutate_** button for each DNA

**Comment by AndreyAttr** [comment]
Update: for task #43 @AndreyAttr added **Mutate** button for each gene and it reveal new problems connected with this _**ugly workaround**_:
1. Add 2 genes and click **Mutate** button on first of them - it doesn't mutate first gene, instead of mutating first gene it will mutate second(**the LAST added one**):
https://www.screencast.com/t/HxyjNA7J9X
The same problem - we lost AppState with all subscriebers and subscriptions for first gene, so we lost behaviour too.

2. After clicking on one of gene's **MUTATED** sites button **Mutate** stop working at all:
![2017-06-11_2319](https://user-images.githubusercontent.com/8319203/27014200-963764bc-4efc-11e7-8028-7895029536e2.png)

**Comment by AndreyAttr** [comment]
# This issue blocks pull request #41. It must be fixed in nearest time in specifc branch(pull request was reverted and by reverting that reverted pull request was created specific branch - `revert-42-revert-41-angular` where it should be fixed)

**Comment by AndreyAttr** [comment]
In gene.component.ts:

1. we do not use common AppState: **private appState: AppState** which we inject through constructor(it's a source of this mistake). Instead of using it we recreate AppState each time when we cretate gene.service(it uses mutation service and mutation service itself require AppState instance). So here we have a source of problem:
`let geneService = DI.resolve<GeneService>(GeneService, geneServiceProvider,{provide: DNA_ENUM_TOKEN, useValue: this.dna}, mutationServiceProvider, AppState);`

2. Individual mutation button's code(#43)  contains error:
```
mutateGene(){
        this.stopPropagation(event);
        this.mutationEnabled = !this.mutationEnabled;
        this.appState.state.mutationChange(this.mutationEnabled);       //TODO: this mutation only for one Gene. It can't influence whole AppState mutationEnabled property. Must be fixed!
    }
```
We update common AppState! We have prop for each component instance for that purpose. We shouldn't touch common AppState as we do right now.

**Comment by tapy-lappy** [comment]
> Also - it works(switchs mutation) only on last added DNA. If you remove it - it won't work. So this workaround produces bug by itself.

**fixed**

>1. Add 2 genes and click Mutate button on first of them - it doesn't mutate first gene, instead of mutating first gene it will mutate second(the LAST added one)

**_fixed,_** but there still is a problem with #43 as @AndreyAttr descirbed in the post above:

> We update common AppState! We have prop for each component instance for that purpose. We shouldn't touch common AppState as we do right now.

This is not connected with this issue and should be fixed into #43 . When click individual Mutate button - it updates all genes - @AndreyAttr needed fix for that. I working into  _**revert-42-revert-41-angular**_ branch and it doesn't contain appropriate changes for #43. The same about individual Mutate button:
> After clicking on one of gene's MUTATED sites button Mutate stop working at all:

But I see the same behaviour for common Mutate button. Will try to clarify.

**Comment by tapy-lappy** [comment]
Added additional fix for method:
`mutate()`
there we need also use **Singleton AppState** instead of wiping existing instance of AppState with all assigned subscribers. It must fix following problem:

> After clicking on one of gene's MUTATED sites button Mutate stop working at all:

@AndreyAttr please merge my changes from  **_revert-42-revert-41-angular_** to your branch and check

**Comment by AndreyAttr** [comment]
@tapy-lappy, there is a problem with [your commit  **_c2938b3_**](https://github.com/AndreyAttr/Evo/commit/c2938b34f63e7d31482efd0248954d7ccc48abd1). There a used **provider** instead of **provide** and it's cause problem in my branch. Please fix it.

**Comment by tapy-lappy** [comment]
Done
