### ISSUE TITLE
ObjectHelper.deepCopy()

### ISSUE THREAD

**Issue by AndreyAttr** [AndreyAttr/Evo#76]
- [x] ObjectHelper should have deepTreeCopy() to use it to simple resolve this ugly solution:
```
 const gene:Gene = {
            name: this.gene.name,
            id: this.gene.id,
            sites: this.gene.sites,
            isMutated: this.gene.isMutated,
            //mutationSites: formModel.formGroups,      //TODO: Bad - need deep copy
            mutationSites: mutatedSites,                //Done
            description: formModel.description as string
        };
```
it should proccess nested items & arrays & nested arrays correctly by using already existed deepCopy() & deepCopyArray() methods. **Update**: it would be nice have 3 overloads with the same name **deepCopy()** to process simple flat items/arrays of items/tree items properly.

**Comment by AndreyAttr** [comment]
Overloads doesn't work:
```
//Workaround: commented, because overload doesn't work with generic types. It works properly with non-generic types
//Workaround: but it sees only first version of overload for generics and doesn't see others.
```
Logic for this task has finished, but we have some parts of application which must be refactored to apply these new changes, as descriebed into https://github.com/AndreyAttr/Evo/issues/65. Actually, untill we merge these changes to **angular** branch it's a blocker task

**Comment by tapy-lappy** [comment]
I found not obvious problems with **deepCopy()**. Problems in following:
- [x] it losts the _**type**_ of copied nested property(sub-item) - absent type **_Site_** onto second picture
- [x] it doesn't copy computable properties - see property **_name_** of Site item on second picture

![original_item](https://user-images.githubusercontent.com/29359567/29082916-bb2bcbd2-7c6f-11e7-9034-b3504ae62db8.png)

![deep_copy](https://user-images.githubusercontent.com/29359567/29082925-beef3f6a-7c6f-11e7-98bb-733d2176bf66.png)

**Comment by AndreyAttr** [comment]
No, that workaround is unappropriate. It will cause many problems in future. I have to reject. Will try to find other solution

**Comment by AndreyAttr** [comment]
This issue is a blocker for #65

**Comment by AndreyAttr** [comment]
So pull request #90 about workaround may be rejected - this is correct aproach which fixed @tapy-lappy 's comment https://github.com/AndreyAttr/Evo/issues/76#issuecomment-321009387
